Vagrant.configure("2") do |config|

  config.vm.define "server02" do |server02|
    server02.vm.box = "ubuntu/bionic64"
	server02.vm.network "private_network", ip: "10.0.0.12"
	server02.vm.hostname = "server02"
	server02.vm.network "forwarded_port", guest: 80, host: 8002
	server02.vm.provision :shell, inline: "apt install curl -y && curl -fsSL https://get.docker.com -o get-docker.sh && sudo sh ./get-docker.sh"
  end
end
