Vagrant.configure("2") do |config|

  config.vm.define "server01" do |server01|
    server01.vm.box = "ubuntu/bionic64"
	server01.vm.network "private_network", ip: "192.168.99.11"
	server01.vm.hostname = "server01"
	server01.vm.network "forwarded_port", guest: 80, host: 8001
	server01.vm.provision :shell, inline: "apt install curl -y && curl -fsSL https://get.docker.com -o get-docker.sh && sudo sh ./get-docker.sh"
  end
end
