Vagrant.configure("2") do |config|

  config.vm.define "server03" do |server03|
    server03.vm.box = "ubuntu/bionic64"
	server03.vm.network "private_network", ip: "10.0.0.13"
	server03.vm.hostname = "server03"
	server03.vm.network "forwarded_port", guest: 80, host: 8003
	server03.vm.provision :shell, inline: "apt install curl -y && curl -fsSL https://get.docker.com -o get-docker.sh && sudo sh ./get-docker.sh"
  end
end
